"""Compatibility facade for executable Continuity V1.2 contracts."""

from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import json
import re
from typing import Any, Mapping, Sequence
import unicodedata

from _house_continuity_v1_2_contract_primitives_v0 import (
    HouseContinuityV12ContractError,
    MAX_COMPLETE_UNIT_IDS,
    MAX_RECEIPT_IDS,
    canonical_json_bytes,
    canonical_sha256,
    normalize_scope,
)
from _house_continuity_v1_2_contract_items_events_v0 import (
    CREATION_SEED_SCHEMA_VERSION,
    ITEM_KINDS,
    LIFECYCLE_STATES,
    MAX_LINKED_ITEM_IDS,
    RESOLUTION_REASONS,
    SCOPE_BINDING_EVENT_SCHEMA_VERSION,
    SCOPE_BINDING_SCHEMA_VERSION,
    SCOPE_KINDS,
    SOLEN_CREATABLE_KINDS,
    SUMMARY_MAX_CHARS,
    WORKING_SET_EVENT_KINDS,
    WORKING_SET_EVENT_SCHEMA_VERSION,
    WORKING_SET_ITEM_SCHEMA_VERSION,
    validate_creation_seed_collision,
    validate_creation_seed_registry,
    validate_event_chains,
    validate_item_kind_payload,
    validate_scope_binding,
    validate_scope_binding_event,
    validate_working_set_event,
    validate_working_set_item,
)
from _house_continuity_v1_2_contract_capabilities_context_v0 import (
    CAPABILITY_OFFER_SCHEMA_VERSION,
    CAPABILITY_SCHEMA_VERSION,
    COMMANDABLE_OPERATION_KINDS,
    COMMAND_CONTEXT_AUTHORITY,
    COMMAND_CONTEXT_MAX_BINDING_CHOICES,
    COMMAND_CONTEXT_MAX_CREATE_OFFERS,
    COMMAND_CONTEXT_MAX_ITEMS,
    COMMAND_CONTEXT_MAX_UTF8_BYTES,
    COMMAND_CONTEXT_SCHEMA_VERSION,
    CONTEXTUAL_RESTATEMENT_CANONICALIZATION_CODE,
    FALSE_SCOPE_CONFLICT_CANONICALIZATION_CODE,
    INTENT_PROTOCOL_VERSION,
    INTENT_SCHEMA_VERSION,
    LEGACY_FALSE_SCOPE_CANONICALIZATION_CODE,
    MAX_TOTAL_OPERATIONS,
    NO_DELTA_CANONICALIZATION_CODES,
    PROVISIONAL_BINDING_CHOICES,
    SEMANTIC_NOVELTY_COMPARISON_VERSION,
    SEMANTIC_NOVELTY_EVIDENCE_SCHEMA_VERSION,
    SEMANTIC_NOVELTY_MARKER_NAMESPACE,
    SEMANTIC_NOVELTY_MARKER_VERSION,
    SEMANTIC_NOVELTY_POLICY_FIELD,
    SEMANTIC_NOVELTY_POLICY_VERSION,
    SEMANTIC_EVALUATION_FIELD,
    SEMANTIC_EVALUATION_SCHEMA_VERSION,
    SEMANTIC_EVALUATION_REQUEST_SCHEMA_VERSION,
    SEMANTIC_EVALUATION_RELATIONS,
    SEMANTIC_OPERATION_KINDS,
    CANONICALIZATION_MARKER_COMPATIBILITY,
    AUTHORITATIVE_REAFFIRMATION_CANONICALIZATION_CODE,
    authoritative_projection_sha256,
    validate_semantic_evaluation_request,
    validate_capability_offer,
    validate_command_context,
    validate_continuity_intent,
    validate_intent_against_capability,
    validate_intent_against_context,
    validate_intent_capability,
    is_no_delta_canonicalization,
)
from _house_continuity_v1_2_contract_participant_authorship_v0 import (
    ASTEL_COMMAND_SCHEMA_VERSION,
    ASTEL_CONFIRMATION_SCHEMA_VERSION,
    JOINT_ATTESTATION_SCHEMA_VERSION,
    canonical_astel_semantic_command,
    validate_astel_confirmation_capability,
    validate_astel_explicit_command,
    validate_astel_reviewed_command_against_capability,
    validate_joint_attestation,
)
from _house_continuity_v1_2_contract_outbox_fence_coverage_v0 import (
    APPLICATION_FENCE_RECEIPT_SCHEMA_VERSION,
    APPLICATION_FENCE_SCHEMA_VERSION,
    COVERAGE_EVICTION_MATRIX,
    OUTBOX_SCHEMA_VERSION,
    OUTBOX_STATES,
    UNIT_COVERAGE_SCHEMA_VERSION,
    decide_application_fence,
    validate_application_fence,
    validate_exact_outbox_retry,
    validate_outbox_against_capability,
    validate_outbox_bundle,
    validate_outbox_transition,
    validate_unit_coverage,
)
from _house_continuity_v1_2_contract_exact_units_anchors_v0 import (
    COMPLETE_UNIT_SCHEMA_VERSION,
    EXACT_ANCHOR_SCHEMA_VERSION,
    validate_complete_continuity_unit,
    validate_exact_anchor_ref,
)
from _house_continuity_v1_2_contract_generation_identity_v0 import (
    GENERATION_IDENTITY_SCHEMA_VERSION,
    derived_house_cache_signature,
    validate_generation_identity_evidence,
)

EXECUTABLE_SCHEMA_VERSIONS = frozenset(
    {
        COMMAND_CONTEXT_SCHEMA_VERSION,
        INTENT_SCHEMA_VERSION,
        ASTEL_COMMAND_SCHEMA_VERSION,
        ASTEL_CONFIRMATION_SCHEMA_VERSION,
        JOINT_ATTESTATION_SCHEMA_VERSION,
        CAPABILITY_OFFER_SCHEMA_VERSION,
        CAPABILITY_SCHEMA_VERSION,
        UNIT_COVERAGE_SCHEMA_VERSION,
        OUTBOX_SCHEMA_VERSION,
        APPLICATION_FENCE_SCHEMA_VERSION,
        GENERATION_IDENTITY_SCHEMA_VERSION,
        CREATION_SEED_SCHEMA_VERSION,
        SCOPE_BINDING_SCHEMA_VERSION,
        WORKING_SET_ITEM_SCHEMA_VERSION,
        WORKING_SET_EVENT_SCHEMA_VERSION,
        SCOPE_BINDING_EVENT_SCHEMA_VERSION,
        EXACT_ANCHOR_SCHEMA_VERSION,
        COMPLETE_UNIT_SCHEMA_VERSION,
        SEMANTIC_EVALUATION_SCHEMA_VERSION,
        SEMANTIC_EVALUATION_REQUEST_SCHEMA_VERSION,
    }
)

__all__ = [
    "ASTEL_CONFIRMATION_SCHEMA_VERSION",
    "CAPABILITY_OFFER_SCHEMA_VERSION",
    "CONTEXTUAL_RESTATEMENT_CANONICALIZATION_CODE",
    "AUTHORITATIVE_REAFFIRMATION_CANONICALIZATION_CODE",
    "FALSE_SCOPE_CONFLICT_CANONICALIZATION_CODE",
    "COVERAGE_EVICTION_MATRIX",
    "EXECUTABLE_SCHEMA_VERSIONS",
    "GENERATION_IDENTITY_SCHEMA_VERSION",
    "HouseContinuityV12ContractError",
    "JOINT_ATTESTATION_SCHEMA_VERSION",
    "LEGACY_FALSE_SCOPE_CANONICALIZATION_CODE",
    "OUTBOX_STATES",
    "SOLEN_CREATABLE_KINDS",
    "SEMANTIC_NOVELTY_COMPARISON_VERSION",
    "SEMANTIC_NOVELTY_EVIDENCE_SCHEMA_VERSION",
    "SEMANTIC_NOVELTY_MARKER_NAMESPACE",
    "SEMANTIC_NOVELTY_MARKER_VERSION",
    "SEMANTIC_NOVELTY_POLICY_FIELD",
    "SEMANTIC_NOVELTY_POLICY_VERSION",
    "SEMANTIC_EVALUATION_FIELD",
    "SEMANTIC_EVALUATION_SCHEMA_VERSION",
    "SEMANTIC_EVALUATION_REQUEST_SCHEMA_VERSION",
    "SEMANTIC_EVALUATION_RELATIONS",
    "CANONICALIZATION_MARKER_COMPATIBILITY",
    "UNIT_COVERAGE_SCHEMA_VERSION",
    "canonical_astel_semantic_command",
    "canonical_json_bytes",
    "canonical_sha256",
    "derived_house_cache_signature",
    "normalize_scope",
    "authoritative_projection_sha256",
    "validate_application_fence",
    "decide_application_fence",
    "validate_astel_confirmation_capability",
    "validate_astel_reviewed_command_against_capability",
    "validate_astel_explicit_command",
    "validate_capability_offer",
    "validate_command_context",
    "validate_semantic_evaluation_request",
    "validate_complete_continuity_unit",
    "validate_continuity_intent",
    "validate_creation_seed_registry",
    "validate_creation_seed_collision",
    "validate_exact_anchor_ref",
    "validate_generation_identity_evidence",
    "validate_intent_against_context",
    "validate_intent_against_capability",
    "validate_intent_capability",
    "is_no_delta_canonicalization",
    "validate_item_kind_payload",
    "validate_joint_attestation",
    "validate_outbox_bundle",
    "validate_outbox_against_capability",
    "validate_outbox_transition",
    "validate_exact_outbox_retry",
    "validate_scope_binding",
    "validate_scope_binding_event",
    "validate_event_chains",
    "validate_working_set_event",
    "validate_working_set_item",
    "WORKING_SET_EVENT_KINDS",
    "validate_unit_coverage",
]
